### ISSUE TITLE
experimentr-like table support

### ISSUE THREAD

**Issue by richfitz** [traitecoevo/rrqueue#1]
Given a data.frame `d`, and function `f` run the equivalent of

``` r
f(d[1,])
f(d[2,])
...
```

or

``` r
do.call("f", d[1,])
do.call("f", d[2,])
...
```

rather than having to go through `rrqlapply` explicitly.  Perhaps offer the same progress bars though?

**Comment by richfitz** [comment]
@dfalster: Ideas on interface here?

**Comment by dfalster** [comment]
Was about to comment but I see you've already implemented. We'll try that and refine as needed.

**Comment by richfitz** [comment]
If you have thoughts, you can still comment here or on the implementation.  What I put together is not perfect but it gets us going with the mortality_bci stuff and matches the experimentr use case reasonably well.
