### ISSUE TITLE
Using rrqueue to examine cluster progress from another machine

### ISSUE THREAD

**Issue by jscamac** [traitecoevo/rrqueue#24]
Hi @richfitz I've set up an AWS cluster using clusterous and submitted workers using rrqueue from my office iMac.

I've also connected to this cluster from my laptop using `clusterous workon`.
What I can't work out is how I can see the cluster progress from my laptop.
If I try and reconnect to the controller using
`obj <- queue("rrq", redis_host="localhost", packages=packages, sources=sources,  redis_port = 6379)`

and then examine the overview:
`obj$tasks_overview()`

It treats it as a new job queue with zero progress on all the summary statistics.
Looking at `obj$keys` between my iMac and my laptop everything is identical except for `tasks`

Is there an argument I am suppose to set? Or do I need to manually change this `task` id to the same as that on my iMac?

**Comment by richfitz** [comment]
You are connecting to the wrong redis server - localhost:6379 is one on your actual computer, while you want the one that is running through the ssh tunnel that clusterous sets up.  The [instructions for successional_diversity](https://github.com/traitecoevo/successional_diversity#running-on-clusterous) are probably most useful - notice that we're connecting to a high port (31379) which is the one listed in the [clusterous configuration](https://github.com/traitecoevo/successional_diversity/blob/master/clusterous/successional_diversity_env.yml#L41)

**Comment by jscamac** [comment]
Yes. Originally we were forced to used port 31379 because clusterous didn't allow ports below 31000. However, the latest clusterous release does allow ports between 1024-65525 [see here](https://github.com/sirca/clusterous/blob/a39d2fb69da644acdb054461bb5abd83145c3dd1/docs/environment_file.md). So instead of remapping the redis port via the clusterous environment yml using something like `ports: "31379:6379"`. We can simply specify `ports:"6379"`.

Also from the instructions I've got. To connect to the local redis server its just
`obj <- queue("rrq", redis_host="redis", packages=packages, sources=sources)`
while connecting the the cluster redis server you need to change reis_host to "localhost".

**Comment by richfitz** [comment]
If you have a local redis server running, then mapping the tunnelled port to 6379 is not going to work.  Personally I would not map a remote redis instance to the port used for the local one.  I would guess that's the issue here if you're not seeing the queue on connection.

I would personally debug this by using redis-cli to connect to the _hopefully_ remote redis instance.  Run `redis-cli -p <remote_port>`.  Running `PING` should be slower on the remote redis instance (i.e., have noticeable latency).  Running `INFO server` will give you information about the server (look at the os type in particular). Running `SMEMBERS rrqueue:queues` should return queues that Redis knows about.

The part `redis_host="redis"` is presumably only valid within the EC2 configuration.

**Comment by jscamac** [comment]
Sorry for the slow reply. Had to resolve clusterous issues.
Yes you are right. It appears to not find the cluster redis.

Running INFO server on the IMac that created the cluster gives me:

```
127.0.0.1:6379> INFO server
# Server
redis_version:3.0.7
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:f09a0843cc9876c3
redis_mode:standalone
os:Linux 3.13.0-48-generic x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.9.2
process_id:9
run_id:79c07338089f879d0a14f1860fd5061903eba9d0
tcp_port:6379
uptime_in_seconds:55374
uptime_in_days:0
hz:10
lru_clock:1161541
config_file:
```

where as on my laptop it seems to connect to a local redis

```
127.0.0.1:6379> INFO server
# Server
redis_version:3.0.7
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:f18d98c86f53f58a
redis_mode:standalone
os:Darwin 15.3.0 x86_64
arch_bits:64
multiplexing_api:kqueue
gcc_version:4.2.1
process_id:3359
run_id:134f414346d3a8d3a2b27ce00dd16a688297b765
tcp_port:6379
uptime_in_seconds:455416
uptime_in_days:5
hz:10
lru_clock:1161408
config_file:
```

`SMEMBERS rrqueue:queues`
returns `rrq` on both machines.

I've shut down the local redis server using
`redis-cli shutdown`

But despite this I still cannot connect to the clusterous server. I guess next time I'll need to remap the ports.

**Comment by jscamac** [comment]
Solved this one.
Turns out I just need to rerun the environment.yml. (i.e. `clusterous run env.yml`).

Using the same port to local is fine if you're not using redis locally.
